### ISSUE TITLE
Face Landmarks

### ISSUE THREAD

**Issue by DuanWei1234** [damo-cv/RealisDance#43]
Hello, thank you for your code, I notice that the face landmarks are not used in your inference demos, however, face landmarks exists in your paper pipeline. I wonder if you use face landmarks in your checkpoint?

**Comment by theFoxofSky** [comment]
Not used, because turning it on affects the face shape. For example, if you put a fat man as ref image, and inference with a sequence from a slim woman, the face of the man will be distorted when turning on it.

However, it will also bring some positive effects.  For example, it will make the expression obey control.

**Comment by DuanWei1234** [comment]
Thank you for your reply. I have another question, if I use a very small dataset, such as a single video data, to overfit the model and test the effectiveness of the pipeline, will the MSE loss converge within a few steps, such as 1-2K?

**Comment by theFoxofSky** [comment]
> Thank you for your reply. I have another question, if I use a very small dataset, such as a single video data, to overfit the model and test the effectiveness of the pipeline, will the MSE loss converge within a few steps, such as 1-2K?

Have not tried
